//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bincess.Components {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MyResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bincess.Components.MyResources", typeof(MyResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Anchor {
            get {
                object obj = ResourceManager.GetObject("Anchor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Apply_Small {
            get {
                object obj = ResourceManager.GetObject("Apply_Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BackColor {
            get {
                object obj = ResourceManager.GetObject("BackColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bold {
            get {
                object obj = ResourceManager.GetObject("Bold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CancelAnchor {
            get {
                object obj = ResourceManager.GetObject("CancelAnchor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Copy {
            get {
                object obj = ResourceManager.GetObject("Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cut {
            get {
                object obj = ResourceManager.GetObject("Cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Eraser {
            get {
                object obj = ResourceManager.GetObject("Eraser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ForeColor {
            get {
                object obj = ResourceManager.GetObject("ForeColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Indent {
            get {
                object obj = ResourceManager.GetObject("Indent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Italic {
            get {
                object obj = ResourceManager.GetObject("Italic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JustifyCenter {
            get {
                object obj = ResourceManager.GetObject("JustifyCenter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JustifyLeft {
            get {
                object obj = ResourceManager.GetObject("JustifyLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JustifyRight {
            get {
                object obj = ResourceManager.GetObject("JustifyRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Outdent {
            get {
                object obj = ResourceManager.GetObject("Outdent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Paste {
            get {
                object obj = ResourceManager.GetObject("Paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Picture {
            get {
                object obj = ResourceManager.GetObject("Picture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Rule {
            get {
                object obj = ResourceManager.GetObject("Rule", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolbarHandler {
            get {
                object obj = ResourceManager.GetObject("ToolbarHandler", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolbarSeparator {
            get {
                object obj = ResourceManager.GetObject("ToolbarSeparator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UnderLine {
            get {
                object obj = ResourceManager.GetObject("UnderLine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Undo {
            get {
                object obj = ResourceManager.GetObject("Undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 /* 
        /// * WebGroupList.js @Microsoft Visual Studio.NET 2003 &lt;JScript 5.5&gt;
        /// * AfritXia
        /// * 11.12/2006
        /// * 
        /// * 
        /// * 
        /// */
        ///
        /////////////////////////////////////////////////////////////////////////
        /////
        ///// 类 CGroup 参数构造器
        /////
        ///// Parameters:
        /////     groupID, 组标记 ID
        /////     openedImgSrc, 打开状态的图片 URL
        /////     closedImgSrc, 关闭状态的图片 URL
        /////
        ///function CGroup(groupID, openedImgSrc, closedImgSrc)
        ///{
        ///	// 获取切换按钮
        ///	this.m_toggleImageTag = document.getElementById(groupID + &quot;__toggleImage&quot;);
        ///	// 获取项目列表标记
        ///	this.m_itemsTag  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string WebGroupListJS {
            get {
                return ResourceManager.GetString("WebGroupListJS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /* 
        /// * WebTextPane.css @Microsoft Visual Studio.NET 2003 &lt;CSS 2&gt;
        /// * AfritXia
        /// * 07.29/2006
        /// * 
        /// * 控件样式表
        /// * 
        /// */
        ///
        ///.WebTextPane
        ///{
        ///}
        ///
        ///.WebTextPane table
        ///{
        ///}
        ///
        ///.WebTextPane table tr
        ///{
        ///}
        ///
        ///.WebTextPane table tr td
        ///{
        ///	padding: 1px;
        ///}
        ///
        ////* 下拉列表框命令控件 */
        ///.WebTextPane table tr td select.CToolbarDropDownList
        ///{
        ///	font: normal normal normal 12px &quot;Tahoma&quot;;
        ///}
        ///
        ////* 图片按钮命令控件 */
        ///.WebTextPane table tr td image.CToolbarImageButton
        ///{
        ///	border: solid 1px #ffffff;
        ///}
        ///
        ///.WebTextPane table tr td image. [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string WebTextPaneCSS {
            get {
                return ResourceManager.GetString("WebTextPaneCSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /* 
        /// * WebTextPane.js @Microsoft Visual Studio.NET 2003 &lt;JScript 5.5&gt;
        /// * AfritXia
        /// * 07.21/2006
        /// * 
        /// * WebTextPane 控件客户端脚本
        /// * 
        /// */
        ///
        ///
        ////*@cc_on @*/
        ////*@set @DEBUG = true; @*/
        ///
        ///// WebTextPane 控件集合
        ///var g_webTextPaneCollection = new Array();
        ///// 当前的 WebTextPane 控件对象
        ///var g_currWebTextPane = null;
        ///// 当前命令管理器
        ///var g_currCmdManager = null;
        ///
        //////////////////////////////////////////////////////////////////////
        /////
        ///// 类 CWebTextPane 构造器
        /////
        ///
        ///function CWebTextPane()
        ///{
        ///	// 将当前编辑器对象加入到集合
        ///	g_webTextPa [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string WebTextPaneJS {
            get {
                return ResourceManager.GetString("WebTextPaneJS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;toolBar&gt;
        ///	&lt;button&gt;
        ///		&lt;commandID&gt;CMD_FONT&lt;/commandID&gt;
        ///		&lt;tipText&gt;字体&lt;/tipText&gt;
        ///	&lt;/button&gt;
        ///	&lt;button&gt;
        ///		&lt;commandID&gt;CMD_SIZE&lt;/commandID&gt;
        ///		&lt;tipText&gt;字体大小&lt;/tipText&gt;
        ///	&lt;/button&gt;
        ///	&lt;button&gt;
        ///		&lt;commandID&gt;CMD_BACK_COLOR&lt;/commandID&gt;
        ///		&lt;tipText&gt;背景颜色&lt;/tipText&gt;
        ///	&lt;/button&gt;
        ///	&lt;button&gt;
        ///		&lt;commandID&gt;CMD_FORE_COLOR&lt;/commandID&gt;
        ///		&lt;tipText&gt;字体颜色&lt;/tipText&gt;
        ///	&lt;/button&gt;
        ///	&lt;button&gt;
        ///		&lt;commandID&gt;CMD_BOLD&lt;/commandID&gt;
        ///		&lt;tipText&gt;加粗 (Ctrl+B)&lt;/tipText&gt;
        ///	&lt;/button&gt;
        ///	&lt;button&gt;
        ///		&lt;comma [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string WebTextPaneXmlToolTips_ch {
            get {
                return ResourceManager.GetString("WebTextPaneXmlToolTips_ch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;toolBar&gt;
        ///	&lt;button&gt;
        ///		&lt;commandID&gt;CMD_FONT&lt;/commandID&gt;
        ///		&lt;tipText&gt;Font Name&lt;/tipText&gt;
        ///	&lt;/button&gt;
        ///	&lt;button&gt;
        ///		&lt;commandID&gt;CMD_SIZE&lt;/commandID&gt;
        ///		&lt;tipText&gt;Font Size&lt;/tipText&gt;
        ///	&lt;/button&gt;
        ///	&lt;button&gt;
        ///		&lt;commandID&gt;CMD_BACK_COLOR&lt;/commandID&gt;
        ///		&lt;tipText&gt;Background Color&lt;/tipText&gt;
        ///	&lt;/button&gt;
        ///	&lt;button&gt;
        ///		&lt;commandID&gt;CMD_FORE_COLOR&lt;/commandID&gt;
        ///		&lt;tipText&gt;Font Color&lt;/tipText&gt;
        ///	&lt;/button&gt;
        ///	&lt;button&gt;
        ///		&lt;commandID&gt;CMD_BOLD&lt;/commandID&gt;
        ///		&lt;tipText&gt;Bold (Ctrl+B)&lt;/tipText&gt; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string WebTextPaneXmlToolTips_en {
            get {
                return ResourceManager.GetString("WebTextPaneXmlToolTips_en", resourceCulture);
            }
        }

		/// <summary>
		/// 获取资源文件请求 URL
		/// </summary>
		/// <param name="value">文本值，或文件名称</param>
		/// <returns></returns>
		public static string GetResourcesURL(string value)
		{
			return "Bincess.Components.GetRes.aspx?ResID=" + value;
		}
    }
}
